# Generated by Django 6.0.1 on 2026-01-08 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('expense_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('category', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('payment_mode', models.CharField(max_length=50)),
                ('merchant_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.CharField(max_length=100)),
            ],
        ),
    ]
